### ISSUE TITLE
The number of images different from the number on the paper

### ISSUE THREAD

**Issue by yiqiang-chen** [iN1k1/OGRE-Outdoor_Group_Person_Re-Identification_Dataset#1]
Hello,
I just read your paper about group re-identification (https://arxiv.org/abs/1707.09173).
In your paper, you mentioned the ORGE dataset contains approximatively 2500 images of 39 groups. But in this folder, i found 1200+ images of 41 groups. I'd like to know Did you use another version of this dataset in your experiments of the paper?
Thank you.

Yiqiang

**Comment by iN1k1** [comment]
Hi Yiqiang, 
thanks for spotting such a mistake!
The number of groups is 39. It is the same as in the paper, but the indexing is not strictly incremental. Indeed we do now have groups 8 and 9. This is why you still see Group_41, but the total number of groups is 39.
As regards the total number of images, that is a mistake. We counted twice the number of samples. We will update the arxiv submission accordingly!
Thanks again for your careful reading ;)
